### ISSUE TITLE
Error outputting resource ID

### ISSUE THREAD

**Issue by codysoyland** [garnertb/github-runner-vnet#6]
I have been getting an error intermittently when running the `nsg` module. During the process of fetching the resource id (GitHubId) for the module output, it sometimes errors with:

```
module.github_runner_vnet.data.azurerm_resources.github_network_settings: Reading...
module.github_runner_vnet.data.azurerm_resources.github_network_settings: Read complete after 1s [id=resource-638a4aa5-4f16-4a2c-bf6c-db5483552ff1]
╷
│ Error: Invalid index
│ 
│   on ../nsg/outputs.tf line 2, in output "resource_id":
│    2:     value = data.azurerm_resources.github_network_settings.resources[0].tags.GitHubId
│     ├────────────────
│     │ data.azurerm_resources.github_network_settings.resources is empty list of object
│ 
│ The given key does not identify an element in this collection value: the collection has no elements.
```

This seems to only occur on first runs (right after the network settings resource is first created). I assume there is a race condition as the resource is still initializing. If I re-run `terraform apply`, it consistently works again on the second try.

**Comment by pwideman** [comment]
If we go with the ARM template approach, then we don't need this method of retrieving the output. When I first tried the ARM template method of creating `networkSettings` it wasn't deleting the resource but I'm having success with it now after trying it again, I probably was still referencing the `networkSettings` from a GitHub private network configuration, which will prevent its deletion.

I'll submit a PR to standardize on the ARM template approach in both the `nsg` and `firewall` configurations, and update the way we're getting the output.

**Comment by codysoyland** [comment]
@pwideman I was trying to figure out a way to use ARM template outputs to output the `GitHubId` but couldn't figure it out (was trying using `reference(parameters('ns_name'))` per copilot suggestion, but the id was not in the reference object). First time trying to use ARM templates so I am probably missing something. Good luck!

**Comment by pwideman** [comment]
@codysoyland this will get it:

```hcl
output "gh_network_settings_id" {
  value = jsondecode(azurerm_resource_group_template_deployment.network_settings.output_content).gitHubId.value
}
```

**Comment by codysoyland** [comment]
Locally, that fails with error `azurerm_resource_group_template_deployment.network_settings.output_content is "{}"`

**Comment by pwideman** [comment]
Sorry, yeah it requires some extra bits in the template content as well:

```json
{
    ...
    "resources": [
        {
            "type": "GitHub.Network/networkSettings",
            "apiVersion": "[parameters('apiVersion')]",
            "name": "[parameters('name')]",
            "location": "[resourceGroup().location]",
            "properties": {
                "organizationId": "[parameters('organizationId')]",
                "subnetId": "[resourceId('Microsoft.Network/virtualNetworks/subnets', parameters('vnetName'), parameters('subnetName'))]"
            }
        }
    ],
    "outputs": {
        "gitHubId": {
            "type": "string",
            "value": "[reference(resourceId('GitHub.Network/networkSettings', parameters('name')), parameters('apiVersion'), 'Full').tags.GitHubId]"
        }
    }
}
```
